server:
  port: 9000
spring:
  application:
    name: 'cards'
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active:
      - qa
  config:
    import: 'optional:configserver:http://localhost:8071/'
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    # We can use hostname as well. But when running locally, we dont have hostnames
    # Hostname is preferred when there is a DNS mapping
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: cards
    description: Eazy Bank Cards Application
    version: 1.0.0

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG