server:
  port: 9000
spring:
  application:
    name: 'cards'
  datasource:
    url: jdbc:h2:mem:cards
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active:
      - qa
  config:
    import: 'optional:configserver:http://localhost:8071/'